name: my_new_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  fl_chart: ^1.1.1          
  syncfusion_flutter_gauges: ^32.2.3
  http: ^1.1.0
  intl: ^0.20.2
  path_provider: ^2.1.2  
  flutter_local_notifications: ^20.0.0 
  shared_preferences: ^2.2.4
  share_plus: ^8.0.0
  flutter_background_service: ^5.1.0
  permission_handler: ^12.0.1
  auto_start_flutter: ^1.4.0
  wakelock_plus: ^1.5.1
  workmanager: ^0.9.0+3
  android_alarm_manager_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 #
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/ 

  fonts:
    - family: IndieFlowers
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-VariableFont_wght.ttf
        - asset: fonts/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
    - family: Conrinthia
      fonts:
        - asset: fonts/Corinthia-Bold.ttf
          weight: 700
        - asset: fonts/Corinthia-Regular.ttf
    - family: Google
      fonts:
        - asset: fonts/GoogleSansCode-VariableFont_wght.ttf
        - asset: fonts/GoogleSansCode-Italic-VariableFont_wght.ttf
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/lettuvault_icon.png"
  min_sdk_android: 21