"""auto_migration

Revision ID: 0eb3bd87259b
Revises: 9e57be3f6650
Create Date: 2026-03-08 22:33:18.453159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb3bd87259b'
down_revision: Union[str, Sequence[str], None] = '9e57be3f6650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('humidity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'humidity')
    # ### end Alembic commands ###
