"""consolidate_sensor_to_internal_env

Revision ID: 2bbc2234ab45
Revises: 3c04958bb2c0
Create Date: 2026-03-29 14:35:30.108132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bbc2234ab45'
down_revision: Union[str, Sequence[str], None] = '3c04958bb2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_scans_id', table_name='ai_scans')
    op.drop_table('ai_scans')
    op.drop_index('ix_sensor_readings_id', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.add_column('internal_environment_readings', sa.Column('device_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internal_environment_readings', 'device_id')
    op.create_table('sensor_readings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('humidity', sa.FLOAT(), nullable=True),
    sa.Column('device_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_id', 'sensor_readings', ['id'], unique=False)
    op.create_table('ai_scans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('worm_count', sa.INTEGER(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('image_name', sa.VARCHAR(), nullable=True),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_scans_id', 'ai_scans', ['id'], unique=False)
    # ### end Alembic commands ###
