"""add user_email

Revision ID: 2e977416f02d
Revises: 2bbc2234ab45
Create Date: 2026-04-11 17:51:29.085061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e977416f02d'
down_revision: Union[str, Sequence[str], None] = '422c0f9478e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_config', sa.Column('user_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_config', 'user_email')
    # ### end Alembic commands ###
