"""Add temperature column to scans

Revision ID: 3f4dbefaad45
Revises: 4fcd5f4968e1
Create Date: 2026-03-08 21:15:21.111453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4dbefaad45'
down_revision: Union[str, Sequence[str], None] = '4fcd5f4968e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('temperature', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'temperature')
    # ### end Alembic commands ###
