"""Split into AI and Sensor tables

Revision ID: 97cc91830007
Revises: c38a90594f27
Create Date: 2026-03-14 14:27:23.476620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97cc91830007'
down_revision: Union[str, Sequence[str], None] = 'c38a90594f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('worm_count', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_scans_id'), 'ai_scans', ['id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('worm_count', sa.INTEGER(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('image_name', sa.VARCHAR(), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('humidity', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_ai_scans_id'), table_name='ai_scans')
    op.drop_table('ai_scans')
    # ### end Alembic commands ###
