"""added name column for testing

Revision ID: 9e57be3f6650
Revises: 3f4dbefaad45
Create Date: 2026-03-08 22:23:47.671473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e57be3f6650'
down_revision: Union[str, Sequence[str], None] = '3f4dbefaad45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'name')
    # ### end Alembic commands ###
