"""auto_migration

Revision ID: c38a90594f27
Revises: 0eb3bd87259b
Create Date: 2026-03-08 22:36:41.966614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38a90594f27'
down_revision: Union[str, Sequence[str], None] = '0eb3bd87259b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'box_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('box_id', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
